project_id = "adkpgzxnlxzfojemgsof"

[functions.square-crm]
verify_jwt = false

[functions.square-booking]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false